
version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/base:current
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: InstallPreq
          command: | 
            echo "Installing clang-tidy"
            sudo apt-get update && sudo apt-get install -y clang-tidy
            echo "Installed"
      - run:
          name: Build
          command: | 
            echo "Building"
            mkdir build && cd build
            cmake -S ..
            make -j $(nproc)
            cd ../
            echo "Built"
      - run:
          name: ninjaTest
          command: | 
            cd build
            ./ninja_test --gtest_output=XML
            echo "Testing Done"
      - store_test_results:
              path: build
      - run:
          name: ctest
          command: | 
            echo "Start Testing"
            cd build
            ctest --output-junit results.xml
            echo "Testing Done"
      - store_test_results:
              path: build/results.xml
      - run:
          name: Run Performance Tests
          command: |
            cd build
            for test in build_log_perftest canon_perftest clparser_perftest elide_middle_perftest hash_collision_bench; do
              echo "Running $test"
              ./$test
            done
      - run: 
          name: Run Compile .o and .so Tests
          command: |
            check_success() {
              if [ $? -eq 0 ]; then
                echo "$1"
              else
                echo "$1"
                exit 1
              fi
            }

            cd src/shadowdash

            g++ -std=c++17 -fPIC -c manifest.cc  manifest.h
            check_success ".o compiled successfully"

            g++ -shared -o manifest.so manifest.o
            check_success ".so compiled successfully"

            cd ../..


workflows:
  build-test-workflow: 
    jobs:
      - build-test