# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  ninja:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install ctest, clang-tidy and compiler
          command: |
            sudo apt-get update
            sudo apt-get install -y cmake g++ clang-tidy
      - run:
          name: Copy clang-tidy config
          command: |
            cp .clang-tidy /tmp/.clang-tidy
      - run:
          name: Run clang-tidy, build ninja 
          command: |
              mkdir build
              cd build
              cmake ..
              make
      - run:
          name: Run tests
          command: |
              cd build
              ctest --output-junit results.xml
      - store_test_results:
              path: build


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - ninja
